-- USER SQL
CREATE USER daniel IDENTIFIED BY null ;

-- QUOTAS

-- ROLES
GRANT "DBA" TO daniel WITH ADMIN OPTION;
GRANT "CWM_USER" TO daniel WITH ADMIN OPTION;
GRANT "CTXAPP" TO daniel WITH ADMIN OPTION;
GRANT "SPATIAL_CSW_ADMIN" TO daniel WITH ADMIN OPTION;
GRANT "WFS_USR_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "MGMT_USER" TO daniel WITH ADMIN OPTION;
GRANT "WM_ADMIN_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "OLAP_USER" TO daniel WITH ADMIN OPTION;
GRANT "OLAP_XS_ADMIN" TO daniel WITH ADMIN OPTION;
GRANT "CSW_USR_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "SCHEDULER_ADMIN" TO daniel WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO daniel WITH ADMIN OPTION;
GRANT "AQ_ADMINISTRATOR_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "DELETE_CATALOG_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "OLAPI_TRACE_USER" TO daniel WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES" TO daniel WITH ADMIN OPTION;
GRANT "OWB$CLIENT" TO daniel WITH ADMIN OPTION;
GRANT "OWB_USER" TO daniel WITH ADMIN OPTION;
GRANT "GATHER_SYSTEM_STATISTICS" TO daniel WITH ADMIN OPTION;
GRANT "LOGSTDBY_ADMINISTRATOR" TO daniel WITH ADMIN OPTION;
GRANT "HS_ADMIN_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO daniel WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO daniel WITH ADMIN OPTION;
GRANT "EJBCLIENT" TO daniel WITH ADMIN OPTION;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "JMXSERVER" TO daniel WITH ADMIN OPTION;
GRANT "OLAP_DBA" TO daniel WITH ADMIN OPTION;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO daniel WITH ADMIN OPTION;
GRANT "JAVAIDPRIV" TO daniel WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "JAVADEBUGPRIV" TO daniel WITH ADMIN OPTION;
GRANT "CONNECT" TO daniel WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO daniel WITH ADMIN OPTION;
GRANT "OEM_MONITOR" TO daniel WITH ADMIN OPTION;
GRANT "APEX_ADMINISTRATOR_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "AQ_USER_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "JAVAUSERPRIV" TO daniel WITH ADMIN OPTION;
GRANT "XDB_SET_INVOKER" TO daniel WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER" TO daniel WITH ADMIN OPTION;
GRANT "JAVA_ADMIN" TO daniel WITH ADMIN OPTION;
GRANT "DBFS_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "JAVASYSPRIV" TO daniel WITH ADMIN OPTION;
GRANT "HS_ADMIN_SELECT_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "RESOURCE" TO daniel WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO daniel WITH ADMIN OPTION;
GRANT "OWB_DESIGNCENTER_VIEW" TO daniel WITH ADMIN OPTION;
GRANT "EXECUTE_CATALOG_ROLE" TO daniel WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO daniel WITH ADMIN OPTION;
GRANT "JAVA_DEPLOY" TO daniel WITH ADMIN OPTION;
GRANT "SPATIAL_WFS_ADMIN" TO daniel WITH ADMIN OPTION;
GRANT "ORDADMIN" TO daniel WITH ADMIN OPTION;
GRANT "AUTHENTICATEDUSER" TO daniel WITH ADMIN OPTION;
GRANT "OEM_ADVISOR" TO daniel WITH ADMIN OPTION;
GRANT "XDBADMIN" TO daniel WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES

